name: Update Chart Weekly

on:
  schedule:
    - cron: "0 0 * * 1"  # Exécute chaque lundi à minuit UTC
  workflow_dispatch:  # Permet aussi de l'exécuter manuellement

jobs:
  update-chart:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Fetch new chart data
        run: |
          curl -o chart.html "URL_GENERATION_SCRIPT"

      - name: Commit and push if changed
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add chart.html
          git commit -m "Weekly chart update" || echo "No changes to commit"
          git push
